name = "N3KO SMP 1.18.2"
author = "oatmealine, Cardboxneko, Rya"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe94f21c0718ea2fa2e97a97015d25a594cf30d552187d36cdd8c41bd1b0abb6"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
