name = "N3KO SMP 1.18.2"
author = "oatmealine, Cardboxneko, Rya"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65c9b1c2aecc27441d3325da37ea5af85ce7dfb5ee01420b3cf3cba8383395ca"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2", "1.18-rc3"]
