name = "N3KO SMP 1.18.2"
author = "oatmealine, Cardboxneko, Rya"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c8ee7d3a0db68bdfe84e1679a39816cb916f16839ca083076628c5502009094"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2", "1.18-rc3"]
