name = "N3KO SMP 1.18.2"
author = "oatmealine, Cardboxneko, Rya"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "239c2bc7f0fb01950a7f1896e880c3f325e317e909fd81f109974413b8174039"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2", "1.18-rc3"]
