name = "N3KO SMP 1.18.2"
author = "oatmealine, Cardboxneko, Rya"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a575fb74edc98a71be24806dbce40f51ffda69411363612ab64bf7675ca0d84d"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
