name = "N3KO SMP 1.18.2"
author = "oatmealine, Cardboxneko, Rya"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6b57c84c0072d26671d4724db99ea19cfe4d840dbe5f3e89d23c5c00738928f"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
